const { createClient } = require('@sanity/client');
const fs = require('fs');
const path = require('path');
const https = require('https');

const client = createClient({
  projectId: 'zfw2xsde',
  dataset: 'production',
  useCdn: false, // Always get the freshest data during build
  apiVersion: '2024-01-01',
});

const ASSETS_DIR = path.join(__dirname, '../assets/generated_images');
const CONSTANTS_DIR = path.join(__dirname, '../constants');
const OUTPUT_FILE = path.join(CONSTANTS_DIR, 'generatedContent.ts');

// Ensure directories exist
if (!fs.existsSync(ASSETS_DIR)) {
  fs.mkdirSync(ASSETS_DIR, { recursive: true });
}

// Helper to download an image
function downloadImage(url, filepath) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode === 200) {
        res.pipe(fs.createWriteStream(filepath))
           .on('error', reject)
           .once('close', () => resolve(filepath));
      } else {
        res.resume(); // Consume response data to free up memory
        reject(new Error(`Request Failed With a Status Code: ${res.statusCode}`));
      }
    }).on('error', reject);
  });
}

async function sync() {
  console.log('Fetching POI data from Sanity...');
  
  // GROQ query to get all POIs with their image URLs resolved
  const query = `*[_type == "poi"] | order(yearAsc asc) {
    "id": id.current,
    eraKeys,
    yearLabel,
    titleTop,
    titleBottom,
    description,
    summary,
    relatedIds,
    hotspot,
    "imageUrl": mainImage.asset->url,
    "imageExtension": mainImage.asset->extension
  }`;

  const pois = await client.fetch(query);
  console.log(`Found ${pois.length} POIs. Downloading images...`);

  let tsContent = `// THIS FILE IS AUTO-GENERATED BY sync-content.js\n// DO NOT EDIT MANUALLY\n\n`;
  tsContent += `export const GENERATED_POIS = {\n`;

  for (const poi of pois) {
    let localImagePath = null;
    let requireStatement = 'null';

    if (poi.imageUrl) {
      const filename = `${poi.id}.${poi.imageExtension || 'jpg'}`;
      const filepath = path.join(ASSETS_DIR, filename);
      
      console.log(`Downloading ${filename}...`);
      await downloadImage(poi.imageUrl, filepath);
      
      // The relative path from constants/generatedContent.ts to the downloaded image
      localImagePath = `../assets/generated_images/${filename}`;
      requireStatement = `require("${localImagePath}")`;
    }

    tsContent += `  "${poi.id}": {
    id: ${JSON.stringify(poi.id)},
    eraKeys: ${JSON.stringify(poi.eraKeys)},
    yearLabel: ${JSON.stringify(poi.yearLabel || '')},
    titleTop: ${JSON.stringify(poi.titleTop)},
    titleBottom: ${JSON.stringify(poi.titleBottom)},
    description: ${JSON.stringify(poi.description)},
    summary: ${JSON.stringify(poi.summary || '')},
    relatedIds: ${JSON.stringify(poi.relatedIds || [])},
    hotspot: ${JSON.stringify(poi.hotspot)},
    mainImage: ${requireStatement}
  },\n`;
  }

  tsContent += `};\n`;

  // Create an array format similar to MOCK_CARDS for easy iteration
  tsContent += `\nexport const MOCK_CARDS = Object.values(GENERATED_POIS).map(poi => ({
  id: poi.id,
  eraKeys: poi.eraKeys, // For backward compatibility
  yearLabel: poi.yearLabel,
  titleTop: poi.titleTop,
  titleBottom: poi.titleBottom,
  imageUri: poi.mainImage
}));\n`;

  // Create POI_DETAILS map for backward compatibility
  tsContent += `\nexport const POI_DETAILS = GENERATED_POIS;\n`;
  
  // Create HOTSPOT_POSITIONS map for backward compatibility
  tsContent += `\nexport const HOTSPOT_POSITIONS = Object.fromEntries(
  Object.values(GENERATED_POIS).filter(poi => poi.hotspot).map(poi => [poi.id, poi.hotspot])
);\n`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`✅ Success! Generated ${OUTPUT_FILE}`);
}

sync().catch(console.error);
