const { createClient } = require('@sanity/client');
const fs = require('fs');
const path = require('path');
const https = require('https');

const client = createClient({
  projectId: 'zfw2xsde',
  dataset: 'production',
  useCdn: false, // Always get the freshest data during build
  apiVersion: '2024-01-01',
});

const ASSETS_DIR = path.join(__dirname, '../assets/generated_images');
const CONSTANTS_DIR = path.join(__dirname, '../constants');
const OUTPUT_FILE = path.join(CONSTANTS_DIR, 'generatedContent.ts');

// Ensure directories exist
if (!fs.existsSync(ASSETS_DIR)) {
  fs.mkdirSync(ASSETS_DIR, { recursive: true });
}

// Helper to download an image
function downloadImage(url, filepath) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode === 200) {
        res.pipe(fs.createWriteStream(filepath))
           .on('error', reject)
           .once('close', () => resolve(filepath));
      } else {
        res.resume(); // Consume response data to free up memory
        reject(new Error(`Request Failed With a Status Code: ${res.statusCode}`));
      }
    }).on('error', reject);
  });
}

async function sync() {
  console.log('Fetching CMS data from Sanity...');
  
  // 1. Fetch Eras
  const eraQuery = `*[_type == "era"] {
    "id": id.current,
    name,
    timeframe,
    summary,
    years,
    color,
    borderExplanation,
    "imageUrl": mapAsset.asset->url,
    "imageExtension": mapAsset.asset->extension
  }`;
  
  // 2. Fetch Site Settings
  const settingsQuery = `*[_type == "siteSettings"][0] {
    globalMaps[] {
      startYear,
      "imageUrl": mapAsset.asset->url,
      "imageExtension": mapAsset.asset->extension
    }
  }`;

  // 3. Fetch POIs
  const poiQuery = `*[_type == "poi"] | order(yearAsc asc) {
    "id": id.current,
    eraKeys,
    "eraRefs": eraRefs[]->id.current,
    yearLabel,
    titleTop,
    titleBottom,
    description,
    summary,
    relatedIds,
    hotspot,
    iconType,
    "imageUrl": mainImage.asset->url,
    "imageExtension": mainImage.asset->extension
  }`;

  const [eras, settings, pois] = await Promise.all([
    client.fetch(eraQuery),
    client.fetch(settingsQuery),
    client.fetch(poiQuery),
  ]);

  console.log(`Found ${eras.length} Eras, ${pois.length} POIs.`);

  let tsContent = `// THIS FILE IS AUTO-GENERATED BY sync-content.js\n// DO NOT EDIT MANUALLY\n\n`;

  // --- Process Eras ---
  tsContent += `export const GENERATED_ERAS = {\n`;
  for (const era of eras) {
    let requireStatement = 'null';
    if (era.imageUrl) {
      const filename = `era_${era.id}.${era.imageExtension || 'jpg'}`;
      const filepath = path.join(ASSETS_DIR, filename);
      console.log(`Downloading era map: ${filename}...`);
      await downloadImage(era.imageUrl, filepath);
      requireStatement = `require("../assets/generated_images/${filename}")`;
    }
    tsContent += `  "${era.id}": {
    id: ${JSON.stringify(era.id)},
    name: ${JSON.stringify(era.name)},
    timeframe: ${JSON.stringify(era.timeframe || '')},
    summary: ${JSON.stringify(era.summary || '')},
    years: ${JSON.stringify(era.years || [])},
    color: ${JSON.stringify(era.color || '#2f2b2d')},
    borderExplanation: ${JSON.stringify(era.borderExplanation || '')},
    mapAsset: ${requireStatement}
  },\n`;
  }
  tsContent += `};\n\n`;

  // --- Process Site Settings (Global Maps) ---
  tsContent += `export const GLOBAL_MAPS = [\n`;
  if (settings && settings.globalMaps) {
    for (const gmap of settings.globalMaps) {
      let requireStatement = 'null';
      if (gmap.imageUrl) {
        const filename = `map_${gmap.startYear}.${gmap.imageExtension || 'jpg'}`;
        const filepath = path.join(ASSETS_DIR, filename);
        console.log(`Downloading global map: ${filename}...`);
        await downloadImage(gmap.imageUrl, filepath);
        requireStatement = `require("../assets/generated_images/${filename}")`;
      }
      tsContent += `  { startYear: ${gmap.startYear}, source: ${requireStatement} },\n`;
    }
  }
  tsContent += `];\n\n`;

  // --- Process POIs ---
  tsContent += `export const GENERATED_POIS = {\n`;
  for (const poi of pois) {
    let requireStatement = 'null';

    if (poi.imageUrl) {
      const filename = `${poi.id}.${poi.imageExtension || 'jpg'}`;
      const filepath = path.join(ASSETS_DIR, filename);
      
      console.log(`Downloading POI image: ${filename}...`);
      await downloadImage(poi.imageUrl, filepath);
      
      requireStatement = `require("../assets/generated_images/${filename}")`;
    }

    tsContent += `  "${poi.id}": {
    id: ${JSON.stringify(poi.id)},
    eraKeys: ${JSON.stringify(poi.eraRefs || poi.eraKeys || [])},
    yearLabel: ${JSON.stringify(poi.yearLabel || '')},
    titleTop: ${JSON.stringify(poi.titleTop)},
    titleBottom: ${JSON.stringify(poi.titleBottom)},
    description: ${JSON.stringify(poi.description)},
    summary: ${JSON.stringify(poi.summary || '')},
    relatedIds: ${JSON.stringify(poi.relatedIds || [])},
    hotspot: ${JSON.stringify(poi.hotspot)},
    iconType: ${JSON.stringify(poi.iconType || 'history')},
    mainImage: ${requireStatement}
  },\n`;
  }

  tsContent += `};\n`;

  // Create an array format similar to MOCK_CARDS for easy iteration
  tsContent += `\nexport const MOCK_CARDS = Object.values(GENERATED_POIS).map(poi => ({
  id: poi.id,
  eraKeys: poi.eraKeys,
  yearLabel: poi.yearLabel,
  titleTop: poi.titleTop,
  titleBottom: poi.titleBottom,
  imageUri: poi.mainImage
}));\n`;

  // Create POI_DETAILS map for backward compatibility
  tsContent += `\nexport const POI_DETAILS = GENERATED_POIS;\n`;
  
  // Create HOTSPOT_POSITIONS map for backward compatibility
  tsContent += `\nexport const HOTSPOT_POSITIONS = Object.fromEntries(
  Object.values(GENERATED_POIS).filter(poi => poi.hotspot).map(poi => [poi.id, poi.hotspot])
);\n`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`✅ Success! Generated ${OUTPUT_FILE}`);
}

sync().catch(console.error);
